name: Remote SSH Command
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: login to duckerhub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build & push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tiwaztyr/startprep:latest
          
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.IP_ADRESS}}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && cd ~/starTprep/ && docker pull tiwaztyr/private:latest
